# Generated by Django 3.1.2 on 2020-10-15 15:58

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_drive_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
