# Generated by Django 3.1.2 on 2020-10-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drive_app', '0002_auto_20201015_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
